export const CHAT_REQUEST = "CHAT_REQUEST";
export const CHAT_SUCCESS = "CHAT_SUCCESS";
export const CHAT_FAILURE = "CHAT_FAILURE";

export const ALL_CHAT_REQUEST = "ALL_CHAT_REQUEST";
export const ALL_CHAT_SUCCESS = "ALL_CHAT_SUCCESS";
export const ALL_CHAT_FAILURE = "ALL_CHAT_FAILURE";

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAILURE = "FETCH_CHAT_FAILURE";

export const NEW_CHAT = "NEW_CHAT";

export const ADD_CHAT_TITLE = "ADD_CHAT_TITLE";
